name: Build and Commit Assets

on:
  pull_request:
    # We can add main here too if we feel like we need to.
    # Presumably by the time we get to main assets would have been built and published.
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # This dynamically checks out the PR's branch

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Commit built assets
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -f lib/
          git diff --quiet || git commit -m "Add built assets"
          git push origin HEAD:${{ github.head_ref }}  # This pushes to the right branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
