name: Lint and Build

on:
  pull_request:
    branches: [develop, main] # Runs on pull requests to develop and main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_extensions: js,ts,tsx
          prettier: true
          stylelint: true
          stylelint_extensions: css,scss

  build:
    needs: lint # Ensures that lint job completes successfully before this job starts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # This dynamically checks out the PR's branch
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Commit built assets
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -f lib/
          git commit -m "Add built assets"
          git push origin HEAD:${{ github.head_ref }}  # This pushes to the right branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
